name: 'crypto_analytics'
version: '1.0.0'

profile: 'crypto_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_analytics:
    intermediate:
      +materialized: materialized_view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts