services:

  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  raw-db:
    platform: linux/amd64
    image: postgres:15
    container_name: raw_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: raw_data
    ports:
      - "5434:5432"
    volumes:
      - raw_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d raw_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/analytics
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD}
      AIRFLOW_CONN_AIRBYTE_DEFAULT: airbyte://host.docker.internal:8000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/dbt_profile:/home/airflow/.dbt
    command: airflow db init
    restart: on-failure

  airflow-webserver:
    build: .
    image: custom-airflow-dbt:2.9.3
    container_name: airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/analytics
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_AIRBYTE_DEFAULT: airbyte://host.docker.internal:8000

      DB_HOST: raw-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./dbt:/opt/airflow/dbt
      - ./dbt/my_dbt_project/airflow/dbt_profile:/home/airflow/.dbt
      - ./ingest.py:/opt/airflow/ingest.py
      - ./config.py:/opt/airflow/config.py
    ports:
      - "8081:8080"

    command: airflow webserver
    restart: always

  airflow-scheduler:
    build: .
    image: custom-airflow-dbt:2.9.3
    container_name: airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/analytics
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_AIRBYTE_DEFAULT: airbyte://host.docker.internal:8000
     
      DB_HOST: raw-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./dbt:/opt/airflow/dbt
      - ./dbt/my_dbt_project/airflow/dbt_profile:/home/airflow/.dbt
      - ./ingest.py:/opt/airflow/ingest.py
      - ./config.py:/opt/airflow/config.py

    command: airflow scheduler
    restart: always

volumes:
  postgres_data:
  raw_db_data: