version: 2

sources:
  - name: raw_data
    database: "{{ env_var('DB_NAME', 'raw_data') }}"
  
    schema: raw
    tables:
      - name: airflow_binance_daily
        identifier: binance_daily
      - name: airflow_alpha_vantage
        identifier: alpha_vantage
      - name: airflow_coingecko_daily
        identifier: coingecko_daily
